marinedb/geodata/models.py
# -*- coding: utf-8 -*-
import datetime
import datetime as dt
import json
import os
from uuid import UUID

# import requests
import dateutil.parser
from dateutil.parser import parse
from flask import current_app, request, g
from flask_login import current_user
from geoalchemy2 import Geometry, Geography
from geoalchemy2.comparator import Comparator
from geoalchemy2.shape import to_shape, from_shape
from pandas import to_datetime
from shapely import wkb

from sqlalchemy.dialects.postgresql import JSON, INTERVAL
from sqlalchemy.ext.hybrid import hybrid_property, hybrid_method
from sqlalchemy import asc, desc, distinct, text, Computed, Table
# from sqlalchemy.orm import column_property
import numpy as np
from sqlalchemy.orm import column_property
from werkzeug.urls import url_fix
from werkzeug.utils import secure_filename
from urllib import parse as urlparse

from marinedb.utils import get_db_engine
from marinedb.database import (
    Column,
    db,
    Model,
    ReferenceCol,
    relationship,
    backref,
    SurrogatePK,
    UniqueConstraint,
    DBFileMixin,
    JSONDataFieldMixin #, create_mat_view, MaterializedView,
)

from sqlalchemy.ext.associationproxy import association_proxy

import random
from marinedb.annotation.models import Label, Tag, LabelAssociation
from sqlalchemy.sql import select
from sqlalchemy import func, case
# import timeit
from marinedb.user.models import Group
from modules.flask_restless import ProcessingException
from modules.flask_restless.helpers import count
# from modules.flask_restless.usergroups import APIUserGroupMixin
import math
from timezonefinder import TimezoneFinderL
import pytz


# from modules.flask_restless.materialized_view_factory import MaterializedView, create_mat_view
from modules.flask_restless.mixins import APIModel
from modules.flask_restless.search import search
from modules.flask_restless.usergroups import APIUserGroupMixin
from modules.datatransform.utils import nullifnan

db_engine = get_db_engine()            # for views

tf = TimezoneFinderL()


def get_random_hex_color():
    return "#%06x" % random.randint(0, 0xFFFFFF)


def gc_distance(lat1, lon1, lat2, lon2, math=math):
    deg2rad = 57.29577951308232
    return (6371000 *
            math.acos(math.sin(lat1 / deg2rad) * math.sin(lat2 / deg2rad) +
                      math.cos(lat1 / deg2rad) * math.cos(lat2 / deg2rad) *
                      math.cos(lon2 / deg2rad - lon1 / deg2rad)))


def euclid_dist(x1, y1, x2, y2, math=math):
    return math.pow((math.pow((x2-x1),2) + math.pow((y2-y1),2)),0.5)




class AnnotationPoint(APIModel, Model, SurrogatePK, JSONDataFieldMixin):
    __tablename__ = 'point'
    __mapper_args__ = {'polymorphic_identity': __tablename__}

    x = Column(db.Float(precision=53), unique=False, nullable=True,
               doc="X location of point as a proportion across the frame width (0-1.0, measured from the left, positive right) or `latitude` for map objects")
    y = Column(db.Float(precision=53), unique=False, nullable=True,
               doc="Y location of point as a proportion across the frame height (0-1.0, measured from the top, positive down) or `longitude` for map objects")
    t = Column(db.Float(precision=53), unique=False, nullable=True,
               doc="Number of seconds of annotation relative to `media.start_time` (eg: for video)")
    media_id = ReferenceCol('media', nullable=False, cascade=True, index=True,
               doc="Foreign key `id` of [media](#media) object linked to [point](#point)")
    media = relationship('Media', doc="Related [media](#media) object",
               backref=backref('annotations', passive_deletes=True, lazy="dynamic", doc="List of [point](#point) objects"))
    annotation_set_id = ReferenceCol('annotation_set', nullable=False, cascade=True,
               doc="Foreign key `id` of the parent/origin [annotation_set](#annotation_set). I.e.: the one linked to the initial creation of the [point](#point)")
    annotation_set = relationship('AnnotationSet', doc="Parent/origin [annotation_set](#annotation_set) object",
               backref=backref('points', passive_deletes=True, lazy="dynamic", doc="List of [point](#point) objects"))
    updated_at = Column(db.TIMESTAMP, default=dt.datetime.utcnow, onupdate=dt.datetime.utcnow, doc="Updated time (UTC)")

    def __init__(self, user_id=None, labels_per_point=1, annotation_label=None, set_media=None, x=None, y=None,
                 t=None, row=None, col=None, annotations=None, **kwargs):
        db.Model.__init__(self, **kwargs)

        # condition some values in case
        if x is not None and y is not None:
            self.x, self.y = nullifnan(x), nullifnan(y)
        elif isinstance(row, int) and isinstance(col, int):
            self.pixels = dict(row=row, col=col, polygon=kwargs.pop('polygon', None))

        self.t = nullifnan(t)

        # initialise media object if relevant
        if isinstance(set_media, dict):
            self.set_media = set_media

        if isinstance(annotations, list):  # use passed in annotations
            self.annotations = annotations
        elif isinstance(annotation_label, dict):    # set with annotation_label property setter
            self.annotation_label = annotation_label
        else:                       # initialise with empty labels
            labels_per_point = max(min(labels_per_point, 10), 1) if isinstance(labels_per_point, int) else 1
            for i in range(labels_per_point):
                self.annotations.append(AnnotationLabel(user_id=user_id, annotation_set_id=self.annotation_set_id))
            # self.mungedfile = None

    def __repr__(self):
        return '<AnnotationPoint(ID: {})>'.format(self.id)

    def bbox(self, default_size=0.2, max_dp=3):
        """Returns point, bbox size in format [x,y], [left, top, right, bottom]"""
        try:
            polygon = self.data.get("polygon", None)
            if polygon is not None:
                xs, ys = zip(*polygon)
                return ([round(self.x,max_dp), round(self.y,max_dp)], [max(0.0, round(min(xs)+self.x, max_dp)), max(0.0, round(min(ys)+self.y,max_dp)),
                        min(1.0, round(max(xs)+self.x, max_dp)), min(1.0, round(max(ys)+self.y, max_dp))])
        except Exception as e:
            print("Warning: no bbox found. {}:{}".format(e.__class__, e))
        return (None, None) if self.x is None or self.y is None else \
            ([round(self.x,max_dp), round(self.y,max_dp)], [max(0.0, round(self.x-default_size/2, max_dp)), max(0.0, round(self.y-default_size/2, max_dp)),
             min(1.0, round(self.x+default_size/2, max_dp)), min(1.0, round(self.y+default_size/2, max_dp))])

    @hybrid_property
    def timestamp(self):
        """The in-situ timestamp for when the annotated object was captured/sampled in the media frame.
        Returns `media.timestamp_start + t` if `t` is set, otherwise it just returns `media.timestamp_start` """
        if isinstance(self.t, float):
            return self.media.timestamp_start + dt.timedelta(seconds=self.t)
        return self.media.timestamp_start

    @timestamp.expression
    def timestamp(cls):
        return db.case([(cls.t.isnot(None), db.session.query(Media.timestamp_start + cls.t*db.cast('1 sec'.format(cls.t), INTERVAL)).filter(cls.media_id == Media.id).as_scalar())],
                       else_=db.session.query(Media.timestamp_start).filter(cls.media_id == Media.id).as_scalar())

    @property
    def pose(self):
        """Get closest linked pose to timestamp"""
        return Pose.query.filter(Pose.media_id==self.media_id).order_by(db.asc(Pose.timestamp_proximity(self.timestamp))).first()

    # @hybrid_property
    # def pose(self):
    #     return Pose.query.filter(
    #         Pose.media_id == self.media_id, Pose.lat.isnot(None), Pose.lon.isnot(None), Pose.lat != float('NaN'),
    #         Pose.lon != float('NaN')).order_by(db.asc(Pose.timestamp_proximity(self.timestamp))).first()


    @hybrid_property
    def has_xy(self):
        """BOOLEAN, whether or not the point has x-y coordinates. If `false`, it is a whole-frame annotation, not a point annotation"""
        return self.x is not None and self.y is not None

    @hybrid_method
    def xy_distance(self, x, y):
        """FLOAT, euclidean distance to `x` and `y` (which are proportions of the image width and height)"""
        return euclid_dist(x, y, float(self.x), float(self.y))

    @xy_distance.expression
    def xy_distance(cls, x, y):
        return euclid_dist(x, y, cls.x.cast(db.Float), cls.y.cast(db.Float), math=db.func)

    @has_xy.expression
    def has_xy(cls):
        return db.and_(cls.x.isnot(None), cls.y.isnot(None))

    @property
    def polygon(self):
        """List of lists containing coordinated of vertices for polygons. Coordinates are in proportions of the image (0-1.0).
        For point annotations, measurements are relative to point's xy location. For whole-frame annotations, they are absolute.
        When setting this property, it can be a list of lists or a JSON string which will automatically be converted to a list of lists."""
        return self.data.get('polygon', [])

    @polygon.setter
    def polygon(self, val):
        if isinstance(val, str):
            val = json.loads(val)
        data = self.data or {}
        data['polygon'] = val
        self.data = data

    @property
    def pixels(self):
        """Use to convert `x`, `y` and `polygon` between pixel coordinates from top left to native proportions coords.

        **Returns** `x`, `y` and `polygon` converted to `col`, `row` and `polygon` values in pixel coordinates from top
        left of frame using the pixel width and height of the
        associated [media](#media) object and are set by the model definition as per the `pixel_width`
        and `pixel_height` properties defined in the [media](#media) object resource, but

marinedb/geodata/__init__.py
'''The geodata module.'''

from . import views, models, api

marinedb/geodata/views.py
# -*- coding: utf-8 -*-
import datetime
import json
from time import time

import requests
from flask import Blueprint, request, redirect, url_for, render_template, flash, make_response, \
    send_file, current_app, jsonify, Response, session
from flask.sessions import SecureCookieSessionInterface
from flask_login import login_required, current_user, login_user
from jinja2 import TemplateNotFound

from marinedb.geodata.api import AnnotationSetAPI, MediaAPI
from marinedb.user.models import User
from modules.flask_restless import ProcessingException

blueprint = Blueprint("geodata", __name__, url_prefix='/geodata', static_folder="../static", template_folder="templates")#, template_folder='../templates/geodata'


@blueprint.route("/models/<resource>", defaults={'mode': 'get', 'id': None})
@blueprint.route("/models/<resource>/<mode>", defaults={'id': None})
@blueprint.route("/models/<resource>/<mode>/<id>")
# @login_required
def model_templates(resource, mode, id):
    params = dict(list(request.args.items()))
    query_string = request.query_string
    try:
        return render_template("model_templates/"+resource+"/"+mode+".html", id=id, params=params, query_string=query_string, resource=resource, mode=mode)
    except TemplateNotFound as e:
        return render_template("model_templates/example_model/"+mode+".html", id=id, params=params, query_string=query_string, resource=resource, mode=mode)


@blueprint.route("/explore")
def explore():
    args = request.args.to_dict()
    action_messages = {"newcollection": "Use the options below to select a dataset, apply filters and create a Collection."}
    if args.get('action') in action_messages:
        flash(action_messages[args.get('action')], 'info')
    return render_template("geodata/explore.html", params=args, current_datetime=datetime.datetime.now())


# @blueprint.route("/collection")
# @login_required
# def collection():
#     return render_template("geodata/collection.html", params=request.args.to_dict())

@blueprint.route("/annotation_set/<int:annotation_set_id>")
def annotation_set(annotation_set_id):
    args = request.args.to_dict()
    data = AnnotationSetAPI.get_by_id(annotation_set_id)
    if data is None:
        raise ProcessingException(description="Not found", code=404)
    return render_template("geodata/annotation_set.html", args=args, data=data.instance_to_dict())


@blueprint.route("/annotate/<int:media_id>/<int:annotation_set_id>")
def annotate_media(media_id, annotation_set_id):
    args = request.args.to_dict()
    media_data = MediaAPI.get_by_id(media_id).instance_to_dict()
    annotation_set_data = AnnotationSetAPI.get_by_id(annotation_set_id).instance_to_dict()
    # add point_ids list to preselect point for annotation window loading
    try: args['point_ids'] = json.loads(args.get("point_ids")) if "point_ids" in args else []
    except: args['point_ids'] = []
    return render_template("geodata/annotate_media.html", args=args, media=media_data, annotation_set=annotation_set_data, rendered_at=int(time()))

@blueprint.route("/frame_player/<src>/<action>", methods=["GET", "POST"])
@blueprint.route("/frame_player/<action>", methods=["GET", "POST"], defaults={"src": "framegrabber"})
@blueprint.route("/frame_player", defaults={"action": None, "src": "framegrabber"}, methods=["GET", "POST"])
@login_required
def frame_player(action, src="framegrabber"):
    if action is not None:
        url = current_app.config.get("FRAME_LOGGER_ACTION").get(src) \
            if isinstance(current_app.config.get("FRAME_LOGGER_ACTION"), dict) \
            else current_app.config.get("FRAME_LOGGER_ACTION")
        if url is not None:
            try:
                url = url.format(action=action)
                if request.method == "POST":
                    data = request.get_json()
                    data["remote_addr"] = request.remote_addr
                    response = requests.post(url, json=data)
                else:   #if request.method == "GET":
                    params = request.args.to_dict()
                    params["remote_addr"] = request.remote_addr
                    response = requests.get(url, params=params) #, timeout=2.0)  # timeout after 1 second
                return Response(response=response.content, status=response.status_code, content_type=response.headers['Content-Type'])
            except Exception as e:
                return jsonify({"status": "error", "message": "Cannot reach {} ({})".format(url, e)}), 503
        return jsonify({"status": "error", "message": "URL for {} not configured".format(action)}), 404
    else:
        return render_template("geodata/frame_player.html")

@blueprint.route("/sqcapture")
def sqcapture():
    qsargs = dict(request.args.to_dict())
    if qsargs.get("api_token", False):
        if not current_user.is_authenticated():
            user = User.query.filter_by(api_token=qsargs.get("api_token", False))
            if user.count():
                login_user(user.one())
        # remove api_token from QS and redirect
        del qsargs["api_token"]
        return redirect(url_for('geodata.sqcapture', **qsargs))
    # session_cookie = SecureCookieSessionInterface().get_signing_serializer(current_app)
    # same_cookie = session_cookie.dumps(dict(session))
    response = render_template("geodata/sqcapture.html")
    # response.headers.add("Set-Cookie", f"my_cookie={same_cookie}; Secure; HttpOnly; SameSite=None; Path=/;")
    return response

@blueprint.route("/event_annotation_list/<int:media_collection_id>/<int:annotation_set_id>")
@login_required
def event_annotation_list(media_collection_id, annotation_set_id):
    return render_template("geodata/partials/event_annotation_list.html", annotation_set_id=annotation_set_id, media_collection_id=media_collection_id)



# import requests
# from flask import Response, stream_with_context
# @blueprint.route("/image_proxy")
# def image_proxy():
#     src = request.args.get("camanProxyUrl")
#     req = requests.get(src, stream=True)
#     return Response(stream_with_context(req.iter_content(2048)), content_type=req.headers['content-type'])

marinedb/geodata/templates/geodata/nav.html
<nav class="navbar  navbar-default navbar-fixed-top" role="navigation">
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <span class="navbar-brand"><a href="{{ url_for('public.home') }}"><i class="fa fa-tag" style="color: white;"></i></a>&nbsp;<b>SQ+</b>: <span style="text-transform: uppercase">{{ nav_title }}</span></span>
  </div>
  <div class="collapse navbar-collapse navbar-ex1-collapse">
    <ul class="nav navbar-nav">
        {% if current_user and current_user.is_authenticated() %}
        <li class="dropdown"><a href="#" class="dropdown-toggle" style="border-left: solid 2px #505050; border-right:solid 2px #505050;" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-list-ul"></i> My Data <span class="caret"></span></a>
          <ul id="my-collection-options" class="dropdown-menu" role="menu">
              <li><a href="{{ url_for('geodata.explore') }}?action=newcollection"><i class="fa fa-plus-circle"></i> New Collection</a></li>
              <li>
                  <a href="javascript:void(0)" onclick="dataset_modal.media_collection_groups('{{ data.media_collection.id if data is defined }}','{{ data.id if data is defined }}')">
                  <i class="fa fa-list-ul"></i> My Datasets</a>
              </li>
              <li>
                  <a href="javascript:void(0)" onclick="dataset_modal.manage_groups()">
                  <i class="fa fa-share-alt"></i> My Groups / Memberships</a>
              </li>
          </ul>
        </li>
        {% endif %}

        {% if nav_title == "explore" %}
        <li><a class="explore-tab-link" href="#map" aria-controls="map" role="tab" data-toggle="tab"><i class="fa fa-globe"></i> Map</a></li>
        <li><a class="explore-tab-link" href="#img" aria-controls="img"  role="tab" data-toggle="tab"><i class="fa fa-image"></i> Media</a></li>
        <li><a class="explore-tab-link" href="#dat" aria-controls="dat"  role="tab" data-toggle="tab"><i class="fa fa-bar-chart"></i> Datasets & Stats</a></li>
        {% elif nav_title == "analyse" %}
        <li><a class="explore-tab-link" href="#img" aria-controls="img"  role="tab" data-toggle="tab"><i class="fa fa-tag"></i> Annotate</a></li>
        <li><a class="explore-tab-link" href="#qac" aria-controls="qac"  role="tab" data-toggle="tab"><i class="fa fa-check-square-o"></i> QA/QC</a></li>
        <li><a class="explore-tab-link" href="#dat" aria-controls="dat"  role="tab" data-toggle="tab"><i class="fa fa-bar-chart"></i> Export</a></li>
        {% endif %}


        {% if data is defined %}
            <li>
                <a class="nav-item-data-resource" style="border-right: solid 2px #505050;" href="javascript:void(0)" data-id="{{ data.id }}" data-resource="annotation_set">
                    <i class="fa fa-share-alt fa-fw"></i> Share
                </a>
            </li>
            <li class="navbar-text"
                title="media_collection[ID:{{ data.media_collection.id }}]: {{ data.media_collection.name }}, annotation_set[ID:{{ data.id }}]: {{ data.name }} (created: {{ data.created_at|parse_datestring|humanize() }})">
                <span class="label">
                    <i class="fa fa-th-list"></i> {{ data.media_collection.name }}
                </span>
                <i class="fa fa-caret-right text-danger"></i>
                <span class="label">
                    <i class="fa fa-tag"></i> {{ data.name }}
                </span>
            </li>


{#            <li>#}
{#                <a class="nav-item-data-resource" style="border-left: solid 2px #505050;" href="javascript:void(0)" data-id="{{ data.media_collection.id }}" data-resource="media_collection">#}
{#                    <i class="fa fa-th-list"></i> {{ data.media_collection.name }}#}
{#                </a>#}
{#            </li>#}
{#            <li class="navbar-text"><i class="fa fa-caret-right text-danger"></i></li>#}
{#            <li>#}
{#                <a class="nav-item-data-resource" style="border-right: solid 2px #505050;" href="javascript:void(0)" data-id="{{ data.id }}" data-resource="annotation_set">#}
{#                    <i class="fa fa-tag"></i> {{ data.name }}#}
{#                </a>#}
{#            </li>#}
        {% endif %}
    </ul>

    <ul class="nav navbar-nav navbar-right" style="margin-right: 0">


        <li><a title="More info"  data-toggle="tooltip" data-placement="bottom" href="{{ url_for('public.about') }}"><i class="fa fa-info-circle"></i></a></li>
        {% if current_user and current_user.is_authenticated() %}
            <li><a title="Bug report / feature request" data-toggle="tooltip" data-placement="bottom" href="javascript:void(0)" onclick="open_modal('{{ url_for('public.userissue') }}', {modal_id: 'userissue-modal', modal_class:'modal-md'})"><i class="fa fa-bug"></i></a></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-user"></i> {{ current_user.username }} <span class="caret"></span></a>
              <ul class="dropdown-menu" role="menu">
                <li><a class="navbar-link" href="javascript:void(0)" onclick="user_modal.logout()">Sign out</a></li>
                <li><a href="javascript:void(0)" onclick="user_modal.update('{{ current_user.id }}')">Edit details</a></li>
                <li><a href="javascript:void(0)" onclick="user_modal.api_token()">API Token</a></li>
              </ul>
            </li>
        {% else %}
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-user"></i> Not logged in <span class="caret"></span></a>
              <ul class="dropdown-menu" role="menu">
                <li><a href="javascript:void(0)" onclick="user_modal.login()">Log in</a></li>
                <li><a href="javascript:void(0)" onclick="user_modal.create()">Sign up</a></li>
              </ul>
            </li>
        {% endif %}
    </ul>
  </div>
</nav>